### ISSUE TITLE
Add integration tests to the `sign` package

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/release-sdk#24]
This issue tracks the implementation part of kubernetes/release#2383

Goal is to implement integration tests for the whole `sign` package as well as running them for every PR via prow.

**Comment by xmudrii** [comment]
We discussed how can we implement integration tests on Slack: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1643887529197969?thread_ts=1642591909.041100&cid=CJH2GBF7Y

For completeness, this is how container image signing works:

* cosign pulls an image from an image registry
* the image is signed
* a new signature tag is pushed to the image registry

Therefore, we need an image registry to push/pull images. The easiest way to solve this is to run some registry in the CI (Prow) and use it. In this case, we don't have to worry about quotas or cleaning up the old images. We also don't have to worry about auth — we can run auth-less because the registry is not exposed to the Internet or outside the ProwJob.

Right now, I'm looking at using [Docker Distribution/Registry project](https://github.com/distribution/distribution).

The workflow will be something like this:

* Run Docker Registry as a container (we'll need docker-in-docker, but some jobs already use it, so it's possible)
* Create a very simple image (e.g. `FROM scratch`) and push it to the local registry
* Use the `sign` package to sign the image
* Ensure that the image is signed
  * In this case we don't care about the image content, only that the image is signed

We'll also need to do something similar for file/artifact signing, but the implementation for that is still WIP.

**Comment by saschagrunert** [comment]
Sounds good @xmudrii! While assuming that the tests should run in go code, we may scaffold a dedicated `test/` directory in the root of this repository containing all integration tests.

**Comment by xmudrii** [comment]
The integration tests are now implemented.
/close
